_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.4
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
activation:
    value: leaky_relu
epochs:
    value: 15
hidden_size1:
    value: 256
hidden_size2:
    value: 128
learning_rate:
    value: 0.001
